test.py need to put in the same folder of poi_id.py to run without errors.
